services:
  # This is a work in progress
  # Ruby,
  # web:
  #   build: .
  #   command: bundle exec rails s -p 3000 -b '0.0.0.0'
  #   volumes:
  #     - .:/morph
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - db

  # TODO: Add data volume
  elasticsearch:
    # We're using elasticsearch 7 (rather than the current latest
    # 8.3.3) is because we don't want to bother with authentication
    # and ssl for the time being
    image: elasticsearch:7.17.7
    ports:
      - "9200:9200"
    mem_limit: 1073741824
    environment:
      - "discovery.type=single-node"

  # This is a work in progress
  # TODO: Add data volume
  # TODO: Use a specific version of mysql
  # TODO: MySQL
  # TODO SQLite 3
  # TODO Redis
  # TODO mitmproxy
  # db:
  #   image: mysql
  #   ports:
  #     - "3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: abc123

  # This is a work in progress
  # proxy:
  #   build: docker_images/morph-mitmdump
  #   links:
  #     - web
  #   environment:
  #     MORPH_URL: http://web:3000
  #     MITMPROXY_SECRET: afisdifubekfnasi
