# Install required roles with
# cd provisioning
# ansible-galaxy install -r requirements.yml -p roles
#
# Note: These roles are listed in .gitignore so they are not committed to the git repo

- src: geerlingguy.elasticsearch
  version: 5.1.0

- src: nickhammond.logrotate
  # Version 0.0.3 contains the fix
  # https://github.com/nickhammond/ansible-logrotate/commit/3e0c0895245b451120043a68b313cd1eadccda16
  version: v0.0.3

- src: newrelic.newrelic-infra
  version: 0.6.0

