---
- name: Ensure we have the Passenger key added
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x561F9B9CAC40B2F7 id=AC40B2F7

- name: Ensure we have HTTPS support for APT
  apt: pkg=apt-transport-https

- name: Ensure we have certificates too
  apt: pkg=ca-certificates

- name: Ensure we have the passenger repository
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger noble main'

- name: Install passenger
  apt: pkg=passenger

- name: Install ngninx extras (compiled with Passenger stuff)
  apt: pkg=nginx-extras

- name: Ensure nginx is running
  service: name=nginx state=started
