---
- name: Install apt-transport-https
  apt: pkg=apt-transport-https state=present

- name: Install ca-certificates
  apt: pkg=ca-certificates state=present

- name: Install software-properties-common
  apt: pkg=software-properties-common

# TODO: Doesn't verify fingerprint of key
- name: Ensure that we have the Docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present

- name: Ensure that we have the docker repository
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable'

- name: Ensure that the docker package is installed
  apt: pkg=docker-ce

- name: Configure docker to disable inter-container communication
  copy:
    src: docker
    dest: /etc/default/docker
  notify: restart docker
